name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - release-*

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        sudo apt-get install tree

        # fix permissions
        sudo find . -type f -exec chmod 666 {} \;
        sudo find . -type d -exec chmod 774 {} \;

        sudo find /usr/local/bin -type f -exec chmod 666 {} \;

        #s2i
        curl \
          -L https://github.com/openshift/source-to-image/releases/download/v1.2.0/source-to-image-v1.2.0-2a579ecd-linux-amd64.tar.gz \
          -o release.tar.gz
        sudo tar -C /usr/local/bin -xvf release.tar.gz

        # python dependencies
        python -m pip install --upgrade pip pipenv twine
        pipenv install --dev

    # - name: Lint with flake8instance
    #   run: |
    #     pipenv run pip install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test
      run: |
        bash tests/test-notebooks.sh